#include <zephyr/logging/log.h>
#include <zephyr/drivers/sensor.h>

#include "zbhome_sensor.hpp"
#include "clusters.hpp"

LOG_MODULE_DECLARE(app, LOG_LEVEL_INF);

#ifdef ZB_ZCL_CLUSTER_ID_TEMP_MEASUREMENT
GENERATE_ATTR_VAL_SETTER(temperature, TEMP_MEASUREMENT)
GENERATE_ATTR_SENSOR_VALUE_SETTER(temperature, float, int16_t, ZCL_TEMPERATURE_MEASUREMENT_MEASURED_VALUE_MULTIPLIER)
GENERATE_SENSOR_FULL_FOR_ATTR(temperature, SENSOR_CHAN_AMBIENT_TEMP)
#endif

#ifdef ZB_ZCL_CLUSTER_ID_REL_HUMIDITY_MEASUREMENT
GENERATE_ATTR_VAL_SETTER(humidity, REL_HUMIDITY_MEASUREMENT)
GENERATE_ATTR_SENSOR_VALUE_SETTER(humidity, float, int16_t, ZCL_HUMIDITY_MEASUREMENT_MEASURED_VALUE_MULTIPLIER)
GENERATE_SENSOR_FULL_FOR_ATTR(humidity, SENSOR_CHAN_HUMIDITY)
#endif

#ifdef ZB_ZCL_CLUSTER_ID_PRESSURE_MEASUREMENT
GENERATE_ATTR_VAL_SETTER(pressure, PRESSURE_MEASUREMENT)
GENERATE_ATTR_SENSOR_VALUE_SETTER(pressure, float, int16_t, ZCL_PRESSURE_MEASUREMENT_MEASURED_VALUE_MULTIPLIER)
GENERATE_SENSOR_FULL_FOR_ATTR(pressure, SENSOR_CHAN_PRESS)
#endif

#ifdef ZB_ZCL_CLUSTER_ID_CARBON_DIOXIDE
GENERATE_ATTR_VAL_SETTER(carbon_dioxide, CARBON_DIOXIDE)
GENERATE_ATTR_SENSOR_VALUE_SETTER(carbon_dioxide, float, float, ZCL_CARBON_DIOXIDE_MEASURED_VALUE_MULTIPLIER)
GENERATE_SENSOR_FULL_FOR_ATTR(carbon_dioxide, SENSOR_CHAN_CO2)
#endif