// Generated by zigbee_home on {{ .GeneratedOn }}, version {{ .Version }}


#include <memory>
#include <vector>

#include <zephyr/kernel.h>
#include <zephyr/device.h>

#if CONFIG_RAM_POWER_DOWN_LIBRARY
#include <ram_pwrdn.h>
#endif

#include <dk_buttons_and_leds.h>

#include "zephyr/logging/log.h"
LOG_MODULE_REGISTER(app, LOG_LEVEL_DBG);

#ifdef __cplusplus
extern "C" {
#endif

#include <zb_nrf_platform.h>

#ifdef __cplusplus
}
#endif

#include <zigbee/zigbee_app_utils.h>
#include <zigbee/zigbee_error_handler.h>

// Header only, why not?
#include "device.hpp"

#include "types.hpp"
#include "types_button_handler.hpp"

// Sensors includes
{{- range .Device.Sensors}}
{{- range .Includes}}
#include "{{.}}"
{{- end}}
{{- end}}
// Sensors includes end

// Extender includes
{{- range .Extenders}}
{{- range .Includes}}
#include "{{.}}"
{{- end}}
{{- end}}
// Extender includes end

// Extender top levels
{{- range .Extenders}}
{{- with maybeRenderExtender .Template "top_level" (sensorCtx 0 $.Device nil .)}}
{{.}}
{{- end}}
{{- end}}
// Extender top levels end

// Sensor templates top level
{{- range $i, $sensor := .Device.Sensors}}
{{ $endpoint := (sum $i 1)}}
// -- {{$sensor}}, for endpoint {{$i}}
{{- with maybeRenderExtender $sensor.Template "top_level" (sensorCtx $endpoint $.Device $sensor nil)}}
{{.}}
{{- end}}
// -- {{$sensor}}, for endpoint {{$i}} end
{{- end}}
// Sensor templates top end

#define BUTTON_BIT(btn) BIT(DT_NODE_CHILD_IDX(DT_NODELABEL(btn)))

#define DEVICE_INITIAL_DELAY_MSEC 2000

std::vector<std::shared_ptr<zbhome::types::Component>> components;
std::vector<std::shared_ptr<zbhome::types::Sensor>> sensors;
std::vector<std::shared_ptr<zbhome::types::ZCLCommandHandler>> zclCommandHandlers;

static const uint32_t loop_sleep_milis = {{.Device.General.RunEvery.Milliseconds}};

{{/* This check should be a helper really */}}
{{- if not (eq .Device.Board.NetworkStateLED "") }}
static void toggle_identify_led(uint16_t led_data)
{
	bool led_on = led_data & 1;
	uint8_t led_idx = led_data >> 1;

	led_on = !led_on;

	dk_set_led(led_idx, led_on);
	zb_ret_t err = ZB_SCHEDULE_APP_ALARM(toggle_identify_led,
					     (uint16_t)(led_idx << 1 | led_on),
					     ZB_MILLISECONDS_TO_BEACON_INTERVAL(
						     IDENTIFY_LED_BLINK_TIME_MSEC));
	if (err) {
		LOG_ERR("Failed to schedule app alarm: %d", err);
	}
}
{{- end }}

static void gpio_init(uint32_t factory_reset_button_bit, uint32_t identify_mode_button_bit)
{
	if (!zbhome::setupButtonHandler(factory_reset_button_bit, identify_mode_button_bit))
	{
		LOG_ERR("Cannot init buttons");
	}

	int err = dk_leds_init();
	if (err) {
		LOG_ERR("Cannot init LEDs (err: %d)", err);
	}
}

#ifdef CONFIG_USB_DEVICE_STACK
static void wait_for_console(void)
{
	const struct device *console = DEVICE_DT_GET(DT_CHOSEN(zephyr_console));
	uint32_t dtr = 0;
	uint32_t time = 0;

	/* Enable the USB subsystem and associated HW */
	if (usb_enable(NULL)) {
		LOG_ERR("Failed to enable USB");
	} else {
		/* Wait for DTR flag or deadline (e.g. when USB is not connected) */
		while (!dtr && time < WAIT_FOR_CONSOLE_DEADLINE_MSEC) {
			uart_line_ctrl_get(console, UART_LINE_CTRL_DTR, &dtr);
			/* Give CPU resources to low priority threads */
			k_sleep(K_MSEC(WAIT_FOR_CONSOLE_MSEC));
			time += WAIT_FOR_CONSOLE_MSEC;
		}
	}
}
#endif /* CONFIG_USB_DEVICE_STACK */

/**@brief Callback function for handling ZCL commands.
 *
 * @param[in]   bufid   Reference to Zigbee stack buffer
 *                      used to pass received data.
 */
static void zcl_device_cb(zb_bufid_t bufid)
{
	zb_zcl_device_callback_param_t  *device_cb_param =
		ZB_BUF_GET_PARAM(bufid, zb_zcl_device_callback_param_t);

	LOG_INF("%s id %hd", __func__, device_cb_param->device_cb_id);

	/* Set default response value. */
	device_cb_param->status = RET_OK;

	zb_uint8_t cluster_id;
	zb_uint8_t attr_id;
	zb_uint8_t endpoint_id = device_cb_param->endpoint;

	bool handlerFound = false;

	switch (device_cb_param->device_cb_id) {
	case ZB_ZCL_SET_ATTR_VALUE_CB_ID:
		cluster_id = device_cb_param->cb_param.
			     set_attr_value_param.cluster_id;
		attr_id = device_cb_param->cb_param.
			  set_attr_value_param.attr_id;

		ZB_ZCL_SET_ATTRIBUTE(
			endpoint_id,
			cluster_id,
			ZB_ZCL_CLUSTER_SERVER_ROLE,
			attr_id,
			// This will not work for all types, but good enough for now, until it will not be.
			(zb_uint8_t *)&device_cb_param->cb_param.set_attr_value_param.values.data8,
			ZB_FALSE);

		for (const auto& handler : zclCommandHandlers) {
			if (handler->getEndpoint() != endpoint_id) {
				continue;
			}

			handlerFound = true;
			handler->zclSetAttrValue(&device_cb_param->cb_param.set_attr_value_param);

			// One endpoint will have only one sensor/device,
			// which means that this sensor/device can modify 
			// its clusters as needed based on this command.
			break;
		}

		if (!handlerFound) {
			device_cb_param->status = RET_NOT_IMPLEMENTED;
		}

		break;

	default:
		// if (zcl_scenes_cb(bufid) == ZB_FALSE) {
		device_cb_param->status = RET_NOT_IMPLEMENTED;
		// }
		break;
	}

	LOG_INF("%s status: %hd", __func__, device_cb_param->status);
}

static void loop(zb_bufid_t bufid) 
{
	ZVUNUSED(bufid);

	// -- Extenders start
	{{- range .Extenders}}
	{{- maybeRenderExtender .Template "loop" (sensorCtx 0 $.Device nil .)}}
	{{- end}}
	// -- Extenders end

	{{- range $i, $sensor := .Device.Sensors}}
	{{ $endpointID := (sum $i 1)}}
	// -- {{$sensor}}, for endpoint {{$i}}
	{{ $sensorCtx := (sensorCtx $endpointID $.Device $sensor nil) }}
	{{- with maybeRenderExtender $sensor.Template "loop" $sensorCtx}}
	{
		{{.}}
	}
	{{- else }}
	{
		{{ if eq (typeFromSensor $sensorCtx) ""}}
		sensor_sample_fetch({{$sensor.Label}}_{{$endpointID}});

		{{- range $sensor.Clusters }}
		zbhome_sensor_fetch_and_update_{{.CVarName}}({{$sensor.Label}}_{{$endpointID}}, {{$endpointID}});
		{{- end}}
		{{end}}
	}
	{{- end}}
	// -- {{$sensor}}, for endpoint {{$i}} end
	{{- end}}

	LOG_DBG("start looping %d sensor(s)", sensors.size());
	for (auto& sensor : sensors) {
		sensor->onLoop();
	}

	zb_ret_t zb_err = ZB_SCHEDULE_APP_ALARM(loop,
					0,
					ZB_MILLISECONDS_TO_BEACON_INTERVAL(loop_sleep_milis));
	if (zb_err) {
		LOG_ERR("Failed to schedule app alarm: %d", zb_err);
	}

	if (bufid) {
		zb_buf_free(bufid);
	}
}

int init_templates() {
	// --- Extenders start
	{{- range .Extenders}}
	{{- with (maybeRenderExtender .Template "main" (sensorCtx 0 $.Device nil .))}}
	{
		{{.}}
	}
	{{- end}}
	{{- end}}
	// --- Extenders end

	// --- Sensors start
	{{- range $i, $sensor := .Device.Sensors -}}
	{{ $endpoint := (sum $i 1)}}
	{{- with (maybeRenderExtender $sensor.Template "main" (sensorCtx $endpoint $.Device $sensor nil))}}
	{
		{{.}}
	}
	{{- end}}
	{{- end -}}
	// --- Sensors end

	return 0;
}

// Template function to add object to the correct vector
template <typename T>
void store_component(std::shared_ptr<T> obj) {
    static_assert(std::is_base_of<zbhome::types::Component, T>::value, "value is not derived from Base");
	components.push_back(obj);

	// Probably we can get away with using dynamic_cast instead.
	// It is done only once on startup, so no much harm,
	// but it may save some bytes of the firmware size.
	if constexpr (std::is_base_of<zbhome::types::Sensor, T>::value) {
        sensors.push_back(obj);
    }

	if constexpr (std::is_base_of<zbhome::types::ZCLCommandHandler, T>::value) {
        zclCommandHandlers.push_back(obj);
    }
}

bool setup_components() {
	{{- /* Loop here over all sensors and add them */ -}}
	{{- range $i, $sensor := .Device.Sensors }}
	{
		{{ $endpoint := (sum $i 1) -}}
		// -- {{$sensor}}, for endpoint {{$i}}
		{{- /* 
			We need to possibly have some arguments for components
			For exmaple, for buttons & LEDs we want to have gpio configuration.

			It is a shame that at this point we are using templates to generate arguments,
			as all of this endavor of using C++ & templated functions is 
			to reduce Golang templates needed and move closer to just C++.
			*/ -}}
		{{- $sensorCtx := sensorCtx $endpoint $.Device $sensor nil -}}
		{{- with $componentType := typeFromSensor $sensorCtx -}}
		{{- maybeRenderExtender $sensor.Template "component_constructor_arguments" $sensorCtx}}
		{{- $constructorArgNames := maybeRenderExtender $sensor.Template "component_constructor_argument_names" $sensorCtx}}
		auto component_{{$i}} = std::make_shared<zbhome::components::{{typeFromSensor $sensorCtx}}>({{$constructorArgNames}});
		component_{{$i}}->setEndpoint({{$endpoint}});
		{{ if $sensor.NeedsDevice -}}
		{{- /* 
			Static name for device var is okay, as it is scoped. 
			The macro cannot be put directly in the argument of the function,
			or I don't know how to do it properly.
			*/ -}}
		const struct device * dev = DEVICE_DT_GET(DT_NODELABEL({{$sensor.Label}}));
		component_{{$i}}->setDevice(dev);
		{{- end }}

		if (!component_{{$i}}->setup()) {
			LOG_ERR("{{$sensor.Label}}_{{$endpoint}} failed setup");
			return false;
		};
		store_component(std::move(component_{{$i}}));
		{{ end }}
	}
	{{ end }}

	return true;
}

bool init_zbhome()
{
	gpio_init(FACTORY_RESET_BUTTON, IDENTIFY_MODE_BUTTON);
	// This part is done in Zigbee thread as I had exceptions
	// while trying to run it from main().
	// It should be okay anyway, as without Zigbee init we
	// can't use these anyway..
	if (!setup_components())
	{
		LOG_ERR("could not add some component");
		return false;
	}

	// ZBOSS framework has started - schedule first loop iteration
	// Though if there are no sensors - no need to loop.
	//
	// As a special case - we also will not loop if user requested
	// 'general.runevery' of 0s.
	if (loop_sleep_milis != 0 && sensors.size() != 0)
	{
		int err = ZB_SCHEDULE_APP_ALARM(loop,
										0,
										ZB_MILLISECONDS_TO_BEACON_INTERVAL(
											DEVICE_INITIAL_DELAY_MSEC));
		if (err)
		{
			LOG_ERR("Failed to schedule app alarm: %d", err);
			return false;
		}
	}
	else
	{
		LOG_WRN("No sensors or zero loop sleep - not starting looping. Button and command handlers are still active");
	}

	LOG_DBG("zbhome is initiated");

	return true;
};

void zboss_signal_handler(zb_bufid_t bufid)
{
	zb_zdo_app_signal_hdr_t *signal_header = NULL;
	zb_zdo_app_signal_type_t signal = zb_get_app_signal(bufid, &signal_header);
	zb_ret_t err = RET_OK;

	/* Update network status LED but only for debug configuration */
	#ifdef CONFIG_ZBHOME_DEBUG_LEDS
	zigbee_led_status_update(bufid, ZIGBEE_NETWORK_STATE_LED);
	#endif /* CONFIG_ZBHOME_DEBUG_LEDS */

	/* Detect ZBOSS startup */
	switch (signal) {
	case ZB_ZDO_SIGNAL_SKIP_STARTUP:
		if (!init_zbhome())
		{
			LOG_ERR("cannot initiate zbhome");
		}
		break;
	{{ if not (eq .Device.Board.NetworkStateLED "") }}
	case ZB_ZDO_SIGNAL_LEAVE:
	case ZB_BDB_SIGNAL_DEVICE_FIRST_START:
		// When leaving network - start blinking led.
		ZB_SCHEDULE_APP_CALLBACK(toggle_identify_led, ZIGBEE_NETWORK_STATE_LED << 1 | 0);
		break;
	{{ end }}
	{{ if not (eq .Device.Board.NetworkStateLED "") }}
	case ZB_BDB_SIGNAL_STEERING:
		ZB_SCHEDULE_APP_ALARM_CANCEL(toggle_identify_led,
						   ZB_ALARM_ANY_PARAM);
		// While we will stop blinking it does not mean that 
		// the LED will be in off state on last iteration.
		dk_set_led_off(ZIGBEE_NETWORK_STATE_LED);
		break;
	{{ end }}
	// Sleep case is already handled by default singal handler.
	default:
		break;
	}

	/* Let default signal handler process the signal*/
	ZB_ERROR_CHECK(zigbee_default_signal_handler(bufid));

	/*
	 * All callbacks should either reuse or free passed buffers.
	 * If bufid == 0, the buffer is invalid (not passed).
	 */
	if (bufid) {
		zb_buf_free(bufid);
	}
}


int main(void)
{
	#ifdef CONFIG_USB_DEVICE_STACK
	wait_for_console();
	#endif /* CONFIG_USB_DEVICE_STACK */

	/* Register device context (endpoint) */
	ZB_AF_REGISTER_DEVICE_CTX(&device_ctx);

	/* Register callback for handling ZCL commands. */
	ZB_ZCL_REGISTER_DEVICE_CB(zcl_device_cb);

	/* Init Basic and Identify attributes */
	mandatory_clusters_attr_init();

	/* Init measurements-related attributes */
	measurements_clusters_attr_init();

	int init_result = 0;
	init_result = init_templates();
	if (init_result != 0) {
		return init_result;
	}

	/* Register callback to identify notifications */
	// ZB_AF_SET_IDENTIFY_NOTIFICATION_HANDLER(DEVICE_ENDPOINT_NB, identify_callback);

	#if CONFIG_ZIGBEE_ROLE_END_DEVICE
	/* Enable Sleepy End Device behavior */
	zb_set_rx_on_when_idle(ZB_FALSE);
	#endif

	if (IS_ENABLED(CONFIG_RAM_POWER_DOWN_LIBRARY)) {
		// For some reason this function may result in
		// debugger not being running correctly(at least on nrf52840dk).
		// This can manifest as debugger not stopping on main() entry.
		// To fix it comment out this call.
		//
		// Currently it is commented out as it causes issues when allocating
		// with std::make_shared() when creating components.
		// Hopefully it may be enabled later, if the issue will be resolved.
		//
		// power_down_unused_ram();
	}

	/* Start Zigbee stack */
	zigbee_enable();

	#if CONFIG_ZBHOME_DEBUG_LEDS
	gpio_pin_set_dt({{ if .Device.Board.Debug.IsEnabled}}&{{.Device.Board.Debug.LEDs.Power}}{{else}}none{{end}}, 1);
	#endif /* CONFIG_ZBHOME_DEBUG_LEDS */

	return 0;
}
