# This configuration enables MCUMgr to work over UART
# Additional configuration is enabled in application configuration
# to allow MCUMgr to manage OS and Images at runtime.

CONFIG_MCUBOOT_SERIAL=y

CONFIG_SERIAL=y
CONFIG_CONSOLE=n
CONFIG_UART_CONSOLE=n
CONFIG_NCS_BOOT_BANNER=n
CONFIG_MCUBOOT_BOOT_BANNER=y
CONFIG_BOOT_BANNER=y
CONFIG_PRINTK=y


CONFIG_LOG=n
CONFIG_LOG_MODE_MINIMAL=y
CONFIG_LOG_BACKEND_UART=y
CONFIG_MCUBOOT_LOG_LEVEL_INF=y

# For testing
#CONFIG_BOOT_SERIAL_UART=y
# For production
CONFIG_BOOT_SERIAL_CDC_ACM=y
CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x10000

# This option can be enabled to wait on app boot for DFU connection
CONFIG_BOOT_SERIAL_WAIT_FOR_DFU=n
CONFIG_BOOT_SERIAL_WAIT_FOR_DFU_TIMEOUT=3000
CONFIG_BOOT_SERIAL_NO_APPLICATION=y
# Enter mcuboot at boot if button is pressed
# CONFIG_BOOT_SERIAL_PIN_RESET=y
CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=y

#CONFIG_PM_PARTITION_SIZE_MCUBOOT=0x15000

CONFIG_MCUBOOT_INDICATION_LED=y
#CONFIG_BOOT_SIGNATURE_TYPE_NONE=y


#CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
#CONFIG_CLOCK_CONTROL_NRF_K32SRC_SYNTH=y
#CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y

CONFIG_SERIAL=n
CONFIG_I2C=n
CONFIG_SPI=n
CONFIG_PWM=n
CONFIG_ADC=n
CONFIG_UART_CONSOLE=n
CONFIG_LOG=n

# RTT for debugging (optional)
# CONFIG_USE_SEGGER_RTT=y

# Enable Nordic-specific features
#CONFIG_CAF=y
#CONFIG_CAF_POWER_MANAGER=y   # Enables nRF52 low-power states
CONFIG_NRFX_POWER=y                   # Access to power modes
CONFIG_NRFX_LPCOMP=n