name: Create release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: macos-latest
            artifact: macos-arm64
          - runner: macos-15-intel
            artifact: macos-amd64
          - runner: windows-latest
            artifact: windows-amd64.exe
          - runner: ubuntu-slim
            artifact: linux-amd64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: go.sum
      - name: Build executable
        run: mkdir builds && cd builds && go build -o zigbee_home-${{ matrix.artifact }} ../cmd/zigbee_home/
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: zigbee_home-${{ matrix.artifact }}
          if-no-files-found: error
          path: builds/*

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: zigbee_home*
          merge-multiple: true
      - name: make executable
        run: chmod +x zigbee_home*
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: zigbee_home*
