name: Prepared SDK env

on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  empty:
    runs-on: ubuntu-latest
    env:
      SDK_VERSION: v2.9.2
      # Let zigbee_home know that env is already set up.
      NO_SETUP_ENV: 1
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: go.sum
      - name: Build executable
        run: go build -o zigbee_home ./cmd/zigbee/; chmod +x ./zigbee_home
      - name: Download nrfutil
        run: | 
          wget --progress=dot:mega https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil
          chmod +x nrfutil
      - name: Install Toolchain and SDK managers
        run: |
          ./nrfutil install toolchain-manager sdk-manager

      - name: Restore cached SDK
        id: cache-sdk-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/ncs/toolchains
            ~/ncs/${{ env.SDK_VERSION }}
          key: ${{ runner.os }}-ncs-${{ env.SDK_VERSION }}
      - name: Download Toolchain and SDK
        if: steps.cache-sdk-restore.outputs.cache-hit != 'true'
        run: ./nrfutil sdk-manager install ${SDK_VERSION}
      - name: Verify toolchain and sdk are installed
        run: |
          ./nrfutil toolchain-manager list
          ./nrfutil sdk-manager list --all-fields
      - name: Cache downloaded SDK
        if: steps.cache-sdk-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            ~/ncs/toolchains
            ~/ncs/${{ env.SDK_VERSION }}
          key: ${{ steps.cache-sdk-restore.outputs.cache-primary-key }}

      - name: Build project
        run: |
          ./nrfutil sdk-manager list --all-fields
          export ZEPHYR_BASE=$(./nrfutil sdk-manager list --json | jq -r ".data.versions[] | select(.version == \"${SDK_VERSION}\").dirNames[0] + \"/zephyr\"")
          echo "Found ZEPHYR_BASE at ${ZEPHYR_BASE}."
          ./nrfutil toolchain-manager launch --ncs-version ${SDK_VERSION} -- bash -c './zigbee_home --config ./examples/basic/zigbee.yaml firmware --workdir project build'
